server:
  port: 11300

spring:
  application:
    name: socket-action

socket.in:
  socketChannelConfigList:
    - port: 29394
      beanName: socketServiceImpl1
    - port: 39394
      beanName: socketServiceImpl2
      readTimeout: 10000
    - port: 49394
      beanName: socketServiceImpl3
      readTimeout: 15000
    - port: 59394
      beanName: socketServiceImpl4